# UR5e pick-place 3-task valid split (every 10th traj from each task).

size_buckets = [[256, 192, 41]]

[[directory]]
path = '/home/riftuser/datasets/diffusion_pipe/val/bowl'
num_repeats = 1

[[directory]]
path = '/home/riftuser/datasets/diffusion_pipe/val/cup'
num_repeats = 1

[[directory]]
path = '/home/riftuser/datasets/diffusion_pipe/val/penCase'
num_repeats = 1

[[directory]]
path = '/home/riftuser/datasets/diffusion_pipe/val/bowlBox'
num_repeats = 1
